In [1]:
import numpy as np

sum
all
any

In [3]:
x = np.array([2, 4 , 5 , 6, 7])
x[[-1, 0]]

array([7, 2])

In [4]:
x[x > 5]

array([6, 7])

In [5]:
x > 5

array([False, False, False,  True,  True])

In [6]:
(x > 5).sum()

2

In [7]:
x[x==2]

array([2])

In [8]:
t = x == 2
t.any()

True

In [9]:
e = x % 2 == 0
e

array([ True,  True, False,  True, False])

In [10]:
e.any()

True

In [11]:
a = x < 10
a.all()

True

In [12]:
b = x < 5
b.all()

False

In [13]:
x[b]

array([2, 4])

In [14]:
jungle = np.array(['lion', 'cat', 'lion', 'horse', 'monkey', 'lion'])

In [16]:
c = jungle == 'lion'
c.sum()

3

In [17]:
d = jungle == 'donkey'

In [18]:
d.any()

False

In [19]:
np.sort(x)

array([2, 4, 5, 6, 7])

In [20]:
np.unique(jungle)

array(['cat', 'horse', 'lion', 'monkey'], dtype='<U6')

# File Input Output

In [23]:
# File input output
np.save('data.npy', x)

In [24]:
np.load('data.npy')

array([2, 4, 5, 6, 7])

In [31]:
f = np.random.randn(10, 10)
f

array([[ 0.62294394, -0.69481679,  1.45883217, -0.49566779, -0.14215528,
         0.08233678, -0.03965016, -0.08120792, -0.40269895, -0.53243479],
       [-1.08916267, -0.66972812,  1.79120876,  0.60327942,  1.33671329,
        -0.42812932, -0.06727638, -0.50668452,  0.66750431,  0.50587577],
       [ 0.43820887, -0.0427744 ,  0.42499314,  0.58038575, -0.32469267,
         0.46875801, -0.56556179,  1.00986009,  0.23855572, -1.79959387],
       [ 1.35291307, -0.49974381,  0.17452218,  0.19691837, -2.10427071,
        -1.19773115, -0.76193556, -1.23712741,  1.16782873, -1.3342555 ],
       [-0.34625468,  0.07808887, -2.97482015,  0.19648061, -1.35935459,
         0.35920793,  0.35622865, -1.10732324, -0.34866466, -0.8242401 ],
       [-0.32442933,  0.06443266, -0.25965509, -1.31452885,  0.18458572,
        -2.01538458, -0.93687946, -0.94490969, -0.45331717,  1.14227226],
       [-0.31055604, -0.08075781,  0.76306454,  1.12932363, -1.14238336,
         0.01588673,  0.66580231, -0.45792086

In [32]:
np.save('randomN.npy', f)

In [33]:
s = np.load("randomN.npy")
s.shape

(10, 10)

In [34]:
p = np.random.randn(5, 5)

In [35]:
np.savez('multi.npz', a1 = f, a2 = p)

In [39]:
multi = np.load('multi.npz')
multi['a1']

array([[ 0.62294394, -0.69481679,  1.45883217, -0.49566779, -0.14215528,
         0.08233678, -0.03965016, -0.08120792, -0.40269895, -0.53243479],
       [-1.08916267, -0.66972812,  1.79120876,  0.60327942,  1.33671329,
        -0.42812932, -0.06727638, -0.50668452,  0.66750431,  0.50587577],
       [ 0.43820887, -0.0427744 ,  0.42499314,  0.58038575, -0.32469267,
         0.46875801, -0.56556179,  1.00986009,  0.23855572, -1.79959387],
       [ 1.35291307, -0.49974381,  0.17452218,  0.19691837, -2.10427071,
        -1.19773115, -0.76193556, -1.23712741,  1.16782873, -1.3342555 ],
       [-0.34625468,  0.07808887, -2.97482015,  0.19648061, -1.35935459,
         0.35920793,  0.35622865, -1.10732324, -0.34866466, -0.8242401 ],
       [-0.32442933,  0.06443266, -0.25965509, -1.31452885,  0.18458572,
        -2.01538458, -0.93687946, -0.94490969, -0.45331717,  1.14227226],
       [-0.31055604, -0.08075781,  0.76306454,  1.12932363, -1.14238336,
         0.01588673,  0.66580231, -0.45792086

In [43]:
arr1 = np.arange(1, 11)
arr2 = np.arange(2, 11, 2)
arr3 = np.arange(0, 11, 3 )

In [44]:
arr1.reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [46]:
s = np.savez("three.npz", a1 = arr1, a2 = arr2, a3 = arr3)

In [47]:
d = np.load("three.npz")

In [48]:
d['a1']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
print(d['a2'])
print(d['a3'])
d.keys()

[ 2  4  6  8 10]
[0 3 6 9]


KeysView(<numpy.lib.npyio.NpzFile object at 0x0000027C45C0EB38>)

# Linear Algebra functions

In [53]:
a = np.random.randn(4, 1)
b = np.random.randn(1, 4)
print(a)
print(b)

[[-1.98149511]
 [ 0.05558081]
 [ 1.42346309]
 [ 0.75967499]]
[[-0.59616672  0.46311223 -0.87890278 -0.32100442]]


In [55]:
c = np.dot(a, b)
print(c)

[[ 1.18130144 -0.91765462  1.74154156  0.63606869]
 [-0.03313543  0.02574015 -0.04885012 -0.01784168]
 [-0.84862132  0.65922317 -1.25108567 -0.45693794]
 [-0.45289295  0.35181478 -0.66768046 -0.24385903]]


In [56]:
d = np.diag(a)
d

array([-1.98149511])

In [60]:
e = np.random.randn(4, 4)
print(e)

[[-1.32333183 -1.36730772 -1.23972045 -0.45192953]
 [ 0.34227428  1.20044948  0.00577561  0.60280383]
 [ 0.64349043  0.23114091 -0.15729765 -0.07417916]
 [-2.3997124   0.46488887 -0.73813548 -0.94971001]]
